### ISSUE TITLE
`plakar rm` is broken

### ISSUE THREAD

**Issue by poolpOrg** [poolpOrg/plakar#2]
**Describe the bug**
There is a regression with `plakar rm` causing it to fault when destroying an existing snapshot:

```
% plakar rm d79b854f-8528-41a1-91a5-a3500321919e
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x1027f7d3c]

goroutine 1 [running]:
github.com/poolpOrg/plakar/storage.(*Snapshot).Purge(0x140001700e0, 0x1400022e079, 0x24)
        /Users/gilles/Wip/github.com/poolpOrg/plakar/storage/snapshot.go:433 +0x3c
main.cmd_rm(0x102a54070, 0x140001537a0, 0x140000121d0, 0x1, 0x1)
        /Users/gilles/Wip/github.com/poolpOrg/plakar/cmd/plakar/cmd_rm.go:55 +0x250
main.main()
        /Users/gilles/Wip/github.com/poolpOrg/plakar/cmd/plakar/plakar.go:265 +0xa24
```

**To Reproduce**
1. create a snapshot
2. delete the snapshot

**Expected behavior**
The command should simply return and the snapshot should no longer be available.

**Desktop (please complete the following information):**
 - OS: any

**Additional context**
This was introduced with the rework into packages.

**Comment by poolpOrg** [comment]
fixed in latest commit
